export default {
    ACTIVATION_SUCCESS: 'ACTIVATION_SUCCESS',
    FETCH_REQUEST: 'FETCH_REQUEST',
    VERIFY_COMM_RELAY: 'VERIFY_COMM_RELAY',
    SEND_RESPONSE: 'SEND_RESPONSE',
    STREAM_PUMP: 'STREAM_PUMP',
    STREAM_END: 'STREAM_END'
};
